apiVersion: v1
kind: Namespace
metadata:
  name: gemini-app-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-app-v2
  namespace: gemini-app-ns
  labels:
    app: gemini-app-v2
spec:
  replicas: 1  # Number of replicas for scaling
  selector:
    matchLabels:
      app: gemini-app-v2
  template:
    metadata:
      labels:
        app: gemini-app-v2
    spec:
      containers:
      - name: gemini-app-v2
        image: zr0th/gcloud-ai-hack:latest  
        ports:
        - containerPort: 8000  # The port your app listens on
        # resources:
        #   requests:
          #   memory: "256Mi"
          #   cpu: "50m"
          # limits:
          #   memory: "512Mi"
          #   cpu: "70m"
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gemini-app-svc-v2
  namespace: gemini-app-ns
spec:
  selector:
    app: gemini-app-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Exposes the service externally

