apiVersion: v1
kind: Namespace
metadata:
  name: gemini-app-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-app
  namespace: gemini-app-ns
  labels:
    app: gemini-app
spec:
  replicas: 1  # Number of replicas for scaling
  selector:
    matchLabels:
      app: gemini-app
  template:
    metadata:
      labels:
        app: gemini-app
    spec:
      containers:
      - name: gemini-app
        image: zr0th/gcloud-ai-hack:latest  # Replace with your image path
        ports:
        - containerPort: 8000  # The port your app listens on
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "70m"
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gemini-app-svc
  namespace: gemini-app-ns
spec:
  selector:
    app: gemini-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Exposes the service externally


